default:
  plugins:
    - image
    - link


alternate:
  selector: 'textarea'
  language: 'ru'
  menu: {}
  toolbar: 'media'
  plugins:
    - autolink
    - media
    - image
  setup :
    function(ed) {
      ed.on('init', function()
      {
          this.getDoc().body.style.fontSize = '15px';
          ed.schema.addValidElements('img[*]');
      });
    }