default:
  plugins:
    - image
    - link
    - uploadimage


alternate:
  selector: 'textarea'
  language: 'ru'
  menu: {}
  toolbar: 'media'
  plugins:
    - autolink
    - media
    - image
    - paste
  paste_as_text: 'true'
  setup :
    function(ed) {
      ed.on('init', function()
      {
          this.getDoc().body.style.fontSize = '15px';
      });
    }